In [2]:
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Embedding, LSTM, Dense

from tensorflow.keras.utils import to_categorical

from tensorflow.keras.callbacks import EarlyStopping

from sklearn.utils import shuffle

In [3]:
with open("dataset.txt", "r", encoding="utf-16") as file:
    text = file.read().lower()

print(text)

what is a perceptron?
a perceptron is the simplest form of an artificial neuron.
it receives multiple inputs, performs a calculation, and produces an output.
input x₁
input x₂  ---> [ perceptron ] ---> output
input x₃
a perceptron performs three main operations:
1.	receives inputs
2.	applies weights
3.	produces an output using an activation function
a perceptron can only solve simple linear problems.
why is the perceptron important?
the perceptron introduced the fundamental concepts used in modern neural networks:
•	inputs
•	weights
•	bias
•	activation function
•	learning process
every neural network architecture we study today is built upon these ideas.
key takeaway
perceptron = single artificial neuron
it is the foundation of all neural network architectures.

ann recap
why ann was introduced
a single perceptron is too limited to solve complex problems.
to overcome this limitation, multiple neurons are connected together to form an artificial neural network (ann).
basic architecture


In [ ]:
tokenizer = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n')

tokenizer.fit_on_texts([text])


In [5]:
word_index = tokenizer.word_index

total_words = len(word_index) + 1

print(word_index)

print("Vocabulary Size:", total_words)


{'the': 1, 'ann': 2, 'perceptron': 3, 'is': 4, 'a': 5, 'this': 6, 'of': 7, 'input': 8, 'to': 9, 'an': 10, 'inputs': 11, 'neural': 12, '•': 13, 'it': 14, 'output': 15, 'problems': 16, 'are': 17, 'i': 18, 'artificial': 19, 'and': 20, 'why': 21, 'network': 22, 'these': 23, 'all': 24, 'layer': 25, 'example': 26, 'with': 27, 'sequence': 28, 'sentences': 29, 'love': 30, 'words': 31, 'different': 32, 'cannot': 33, 'form': 34, 'neuron': 35, 'receives': 36, 'multiple': 37, 'performs': 38, 'produces': 39, '1': 40, '2': 41, 'weights': 42, '3': 43, 'activation': 44, 'function': 45, 'can': 46, 'solve': 47, 'important': 48, 'introduced': 49, 'networks': 50, 'learning': 51, 'architecture': 52, 'today': 53, 'key': 54, 'takeaway': 55, 'single': 56, 'together': 57, '↓': 58, 'assumption': 59, 'order': 60, 'does': 61, 'not': 62, 'their': 63, 'meaning': 64, 'data': 65, 'for': 66, 'movie': 67, "don't": 68, 'same': 69, 'however': 70, 'completely': 71, 'word': 72, 'understand': 73, 'difference': 74, 'remember

In [6]:
input_sequences = []

for line in text.split("\n"):

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i + 1]
        input_sequences.append(n_gram_sequence)


In [7]:
for sequence in input_sequences[:10]:
    print(sequence)

[86, 4]
[86, 4, 5]
[86, 4, 5, 3]
[5, 3]
[5, 3, 4]
[5, 3, 4, 1]
[5, 3, 4, 1, 87]
[5, 3, 4, 1, 87, 34]
[5, 3, 4, 1, 87, 34, 7]
[5, 3, 4, 1, 87, 34, 7, 10]


In [8]:
max_sequence_len = max(len(seq) for seq in input_sequences)

In [9]:
max_sequence_len

19

In [10]:
input_sequences = pad_sequences(
    input_sequences,
    maxlen=max_sequence_len,
    padding="pre"
)

In [14]:
print(input_sequences[:5])

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 86  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 86  4  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 86  4  5  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  3  4]]


In [15]:
X = input_sequences[:, :-1]

y = input_sequences[:, -1]

In [16]:
y = to_categorical(
    y,
    num_classes=total_words
)

In [17]:
print("X Shape:", X.shape)

print("y Shape:", y.shape)

X Shape: (298, 18)
y Shape: (298, 195)


In [18]:
print("Vocabulary Size:", total_words)
print("Maximum Sequence Length:", max_sequence_len)
print("Number of Training Sequences:", len(input_sequences))

Vocabulary Size: 195
Maximum Sequence Length: 19
Number of Training Sequences: 298


In [19]:
model = Sequential([
    
    Embedding(input_dim=total_words,
              output_dim=100,
              input_length=max_sequence_len-1),

    LSTM(150),

    Dense(total_words, activation='softmax')

])


c:\Users\ASUS\anaconda3\envs\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [21]:
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

In [23]:
history = model.fit(
    X,
    y,
    epochs=50,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.0134 - loss: 5.2735 
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0268 - loss: 5.2262
Epoch 3/50
 1/10 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.0000e+00 - loss: 5.0719

c:\Users\ASUS\anaconda3\envs\myenv\Lib\site-packages\keras\src\callbacks\early_stopping.py:99: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0268 - loss: 5.1144  
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0336 - loss: 4.9880
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0302 - loss: 4.9521   
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.0302 - loss: 4.9128
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0336 - loss: 4.8687
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0403 - loss: 4.8038
Epoch 9/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0503 - loss: 4.7325
Epoch 10/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0570 - loss: 4.6624
Epoch 11/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0537 - loss: 4.5787
Epoch 12/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0705 - loss: 4.4876
Epoch 13/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0772 - loss: 4.4166
Epoch 14/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.1

In [29]:
seed_text = "This assumption becomes problematic when"

next_words = 6

for _ in range(next_words):

    token_list = tokenizer.texts_to_sequences([seed_text])[0]

    token_list = pad_sequences(
        [token_list],
        maxlen=max_sequence_len-1,
        padding="pre"
    )

    predicted = model.predict(token_list, verbose=0)

    predicted_word = tokenizer.index_word[
        np.argmax(predicted)
    ]

    seed_text += " " + predicted_word

print(seed_text)

This assumption becomes problematic when dealing with language and sequence data
